### ISSUE TITLE
转换后封面图片丢失

### ISSUE THREAD

**Issue by SdKfzTraveller** [Majjcom/ncmppGui#14]
文件1为um-web.extension.v1.10.5工具转换后所得音频文件，具备封面图片；
文件2为此工具转换后所得音频文件，封面图片消失。
大佬救救😭

![屏幕截图 2024-08-23 004314](https://github.com/user-attachments/assets/09810a98-f2cd-4291-ae06-f44caed4f8c2)

**Comment by Majjcom** [comment]
这个软件不加载封面
详情见#6

**Comment by Majjcom** [comment]
用C++做起来太累了，懒得做了😘😭😭
