### ISSUE TITLE
能否增加是否保存封面等信息的选项

### ISSUE THREAD

**Issue by duanzeqing** [Majjcom/ncmppGui#6]
程序似乎默认不保存封面图片等信息，能否增加是否保存封面等信息的选项

**Comment by Majjcom** [comment]
关于音频元数据的问题，在之前的issue也提到过。
回答是：不加。
由于ncm的音频元数据和音频数据是分开存储的，加上这个功能就要额外添加很多东西（包括MP3格式解析，FLAC格式解析），我个人认为这个功能并不是刚需，而且加上费时费力。

所以我选择摆烂😘。

如果有好心人帮我写一点，那我就感激不尽了😭。

以上。
