### ISSUE TITLE
关于输出路径的问题

### ISSUE THREAD

**Issue by nahco365** [Majjcom/ncmppGui#8]
默认的保持为空时不能输出，是否可以实现路径保持为空时输出路径自动到源文件所在文件夹？

**Comment by Majjcom** [comment]
我个人不希望这么做，因为这么做可能会出现一些无法预测的情况
我希望软件的行为是绝对明确的

**Comment by Majjcom** [comment]
最多是输入框内在输入文件后自动填充路径
但这样的话两种输入方式可能又会产生冲突，导致输出目录的不确定性

可能是我有强迫症把😭

**Comment by Majjcom** [comment]
原本的想法是默认输出到用户目录，但是又违背了我个人：不占用系统空间 的原则

所以干脆就没写🤦‍♂️

**Comment by Majjcom** [comment]
如果有什么好的方案可以提一嘴，做个参考😘
